---
# template source: https://github.com/bretfisher/docker-build-workflow/blob/main/templates/call-docker-build.yaml
name: Docker Build

on:
  push:
    branches:
      - main
    # don't rebuild image if someone only edited unrelated files
    paths-ignore:
      - 'README.md'
      - '.github/linters/**'
  pull_request:
    # don't rebuild image if someone only edited unrelated files
    paths-ignore:
      - 'README.md'
      - '.github/linters/**'

# cancel any previously-started, yet still active runs of this workflow on the same branch
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call-docker-build:

    name: Call Docker Build

    # FIXME: fork this repo and update this path to YOUR reusable workflow location
    uses: bretfisher/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main

    # set permissions here to be equal or greater than what's required in the Reusable Workflow
    # Permisions set here for the GITHUB_TOKEN are then passed to the Reusable Workflow
    # Calling permissions must be equal to or greater than these reusable permissions for it to work
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows#supported-keywords-for-jobs-that-call-a-reusable-workflow
    permissions:
      contents: read
      packages: write # needed to push docker image to ghcr.io
      pull-requests: write # needed to create and update comments in PRs
    
    secrets:

      # Only needed if with:dockerhub-enable is true below
      # https://hub.docker.com/settings/security
      # dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      # dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

    with:
      
      # NOTE: there are lots of input options for this reusable workflow
      # read the comments in the inputs area of the reusable workflow for more info
      # https://github.com/BretFisher/docker-build-workflow/blob/main/.github/workflows/reusable-docker-build.yaml

      # Here are just a few of the common defaults

      # dockerhub-enable: false
      # ghcr-enable: true

      # image-names: |
      #   ghcr.io/${{ github.repository }}

      # tag-rules: |
      #   type=raw,value=stable-{{date 'YYYYMMDD'}}-{{sha}},enable={{is_default_branch}},priority=300
      #   type=ref,event=tag,priority=200
      #   type=raw,value=latest,enable={{is_default_branch}},priority=100
      #   type=raw,value=gha-${{ github.run_id }},enable=${{github.event_name == 'pull_request'}},priority=200
      #   type=ref,event=pr,priority=100

      # context: "{{defaultContext}}"
      
      # target:
      
      # platforms: linux/amd64
      
      # comment-enable: true
